### ISSUE TITLE
ChooseOptions / gameLayout 리팩토링

### ISSUE THREAD

**Issue by suyoungDev** [suyoungDev/kpop-master#20]
클린코딩 시급..
난장판임 지금

**Comment by mochapoke** [comment]
- useReducer로 상태관리를 전역으로 할 수 있다면 컴포넌트도 쪼갤 수 있고 좀더 정리가능하지않을까
- 커스텀훅도 쓰고...

**Comment by mochapoke** [comment]
useContext로 함수를 context안에 넣어버릴까?🤔
