### ISSUE TITLE
chooseOption: year수정 및 옵션 추가 예정

### ISSUE THREAD

**Issue by suyoungDev** [suyoungDev/kpop-master#47]
# 주된 이유
year option에서 2020을 제외한 2010년대 같은거는 melon parser에서 가져오는 시간이 너무 오래걸린다!

## 해결 생각
option: year을 없애야 하나 고민 해봐야 할 듯...
아니면 그냥 매년으로 바꾼다거나..(이건 6초정도라서)

**Comment by mochapoke** [comment]
매년도 오바같구 10년주기도 좀 아닌거같고.. 
그냥 커스텀 목록을 만드는게 좋을거같기도...?

**Comment by mochapoke** [comment]
## 추가기능 (예정)

- [ ] custom theme 생성 페이지 (로그인 유저만 가능)
- [ ] theme제목, 노래제목, 아티스트이름, vedioId(optional)
- [ ] 몽고 스키마는 url이랑 연동한 `custom Theme List 스키마`로 만드는게 좋을듯?
- [ ] chooseOptions페이지에서 커스텀 목록 선택해서 플레이 가능

## 삭제기능(예정)
- [ ] year 기능

**Comment by mochapoke** [comment]
## 수정안 (예정)
- [ ] chooseOptions 에서 year 계속 유지
- [ ] mongoDB에서 난이도에 따라 어떻게 가져올지 고민해봐야할 듯...?
- [ ] 어려움은 그냥 DB에서 randomly 가져오면 됨!
- [ ] 난이도해결은... 일단 다 가져온뒤 `rank: (난이도레벨)` 이하 만 컷하고 거기서 pick randomly...?

버젼3에서도 year type 계속 유지할 거임!
